<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>683887be-7dc0-41f2-a6bd-d9241d897a3f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="RCON.Net.Commands.Minecraft.Java" Version="1.1.1" />
    <PackageReference Include="Discord.Net.WebSocket" Version="3.18.0" />
  </ItemGroup>

</Project>
